apiVersion: v1
kind: Pod
metadata:
  name: traducir
  labels:
    app: traducir
spec:
  containers:
  - name: server
    image: caddy:2.6
    ports:
    - containerPort:  80
      hostPort: 1025
      name:  http
    # - containerPort: 443
    #   name: https
    volumeMounts:
    - name: frontend
      mountPath: /srv:z
    - name: caddyfile
      mountPath: /etc/caddy/Caddyfile:z
    - mountPath: /data
      name: caddy_data
    - mountPath: /config
      name: caddy_config
  - name: traducir
    image: api-py
  volumes:
    - name: frontend
      hostPath:
        path: ./website
        type: Directory
    - name: caddyfile
      hostPath:
        path: ./Caddyfile
        type: File
    - name: caddy_data
      persistentVolumeClaim:
          claimName: caddy_data
    - name: caddy_config
      persistentVolumeClaim:
          claimName: caddy_config

